services:
  docs:
    image: {{ devxhub_python.project_slug }}_local_docs
    container_name: {{ devxhub_python.project_slug }}_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./{{ devxhub_python.project_slug }}:/app/{{ devxhub_python.project_slug }}:z
    ports:
      - '9000:9000'
    command: /start-docs